language: bash
sudo: false
os: osx

env:
  global:
  - KERL_BASE_DIR="$TMPDIR"/.kerl
  - KERL_BUILD_BACKEND=git
  - KERL_CONFIGURE_DISABLE_APPLICATIONS='odbc'
  matrix:
  - _KERL_VSN=22.2
  - _KERL_VSN=21.3.8
  - _KERL_VSN=20.3

script:
- ./kerl update releases
- travis_wait 45 ./kerl build "$_KERL_VSN" "$_KERL_VSN"
- ./kerl install "$_KERL_VSN" "install_$_KERL_VSN"
- ./kerl status
- |
  source $(./kerl path install_$_KERL_VSN)/activate
  erl -s crypto -s init stop
  erl_call
  kerl_deactivate
- |
  source $(./kerl path install_$_KERL_VSN)/activate
  ./kerl install-docsh
  kerl_deactivate
  source $(./kerl path install_$_KERL_VSN)/activate
  erl -noshell -eval 'h(proplists).' -s init stop
  kerl_deactivate
- ./kerl delete installation $(./kerl path install_$_KERL_VSN)
- ./kerl delete build "$_KERL_VSN"
